- SAML/README.md
- SAML/saml_config.sh
A more interactive/verbose version of the scripts shown internally at https://sysdig.atlassian.net/wiki/spaces/EN/pages/2099889/SAML+2.0+integration.
> SAML helper script for on-prem config

- agent_deploy/google_gke/sysdig-gke_daemon-set-method/sysdig.jinja
- agent_deploy/kubernetes/sysdig-daemonset.yaml
- agent_deploy/kubernetes/sysdig-rc.yaml
When back-in-time aka memdump is enabled, it requires a larger /dev/shm
filesystem than is normally provided in k8s. To work around this, in the
pod specification create a memory-backed volume and mount it to
/dev/shm.
This allows for having an agent configuration that is eventually
compatible with back-in-time captures so it doesn't have to be changed later.
> Add memdump options to k8s configs.

- SAML/get_saml_config.sh
- SAML/set_saml_config.sh
- Point to `bash` so the `echo -n` works correctly on Mac
- Make separate scripts for setting and getting config
- Turn off the silent option and use verbose instead so we can have the docs tell them to look for 200 OK
> Improve SAML helper scripts

- agent_deploy/kubernetes/sysdig-agent-daemonset-v2.yaml
This dnsPolicy makes the sysdig pods be configured with the right resolver configuration, so that one can use service dns addresses in the appchecks.
> Fix dnsPolicy for example daemonset

- agent_deploy/openshift/sysdig-agent-daemonset-redhat-openshift.yaml
Synchronize dnsPolicy from Kubernetes with OpenShift manifest.
> Add dnsPolicy to sysdig agent in OpenShift

- agent_deploy/kubernetes/sysdig-agent-daemonset-v1.yaml
- agent_deploy/kubernetes/sysdig-agent-daemonset-v2.yaml
- agent_deploy/kubernetes/sysdig-agent-slim-daemonset-v1.yaml
- agent_deploy/kubernetes/sysdig-agent-slim-daemonset-v2.yaml
- agent_deploy/openshift/sysdig-agent-daemonset-redhat-openshift.yaml
If the pod fails to terminate quickly, it will continue to use the probe
module and prevent a new agent pod from starting up successfully. The
default grace period is 30s, and we lower it to 5s to prevent data gaps.
> [SMAGENT-1039] Use a 5s pod termination grace period

- agent_deploy/kubernetes/sysdig-agent-daemonset-v1.yaml
- agent_deploy/kubernetes/sysdig-agent-daemonset-v2.yaml
- agent_deploy/kubernetes/sysdig-agent-slim-daemonset-v1.yaml
- agent_deploy/kubernetes/sysdig-agent-slim-daemonset-v2.yaml
We need this to access the CRI socket, when present.
> Mount whole /run and /var/run inside agent containers [SMAGENT-1209]

- SSO/Google_Oauth/README.md
- SSO/Google_Oauth/google_oauth_config.sh
- SSO/LDAP/README.md
- SSO/LDAP/login_config.sh
- SSO/OpenID_Connect/README.md
- SSO/OpenID_Connect/oidc_config.sh
- SSO/README.md
- SSO/SAML/README.md
- SSO/SAML/saml_config.sh
- SSO/utils.sh
After jumping into a support call I realised these SSO scripts were not working for those users not using Linux. Because of `getopts` not installed by default at macOS and those differences about `getopt` between GNU and BSD, I decided to move backwards accepting only short parameters.
For this PR I'm taking the already approved (but not merged yet) https://github.com/draios/sysdig-cloud-scripts/pull/58 documentation improvement
> Parameter parsing with getopts was failing a macOS

- agent_deploy/kubernetes/sysdig-agent-configmap.yaml
k8s can't end with the pipe....so add a config that nobody will delete which doesn't do anything to make it syntatically valid
> [SMAGENT-1407] add dummy config to default configmap

- agent_deploy/IBMCloud-Kubernetes-Service/install-agent-k8s.sh
The default selector prevents the agent from running on the master node. Modifying the selector is safer than setting `app=sysdig-agent` because other tools may also use the app label, and it's easier because we'll no longer need to label the nodes. This is the idiomatic way recommended by openshift. https://docs.openshift.com/container-platform/4.1/nodes/jobs/nodes-pods-daemonsets.html#nodes-pods-daemonsets-creating_nodes-pods-daemonsets
> [SMAGENT-1697] Override the project's default node selector in openshift

- agent_deploy/kubernetes/sysdig-agent-configmap.yaml
Reverts draios/sysdig-cloud-scripts#72
I'll add this information to this doc page instead: https://sysdigdocs.atlassian.net/wiki/spaces/Monitor/pages/204931201/Elasticsearch
> Revert "add optional app_check to sysdig-agent configmap"

- agent_deploy/kubernetes/sysdig-agent-configmap.yaml
- agent_deploy/kubernetes/sysdig-agent-daemonset-v2.yaml
- agent_deploy/kubernetes/sysdig-agent-service.yaml
- k8s_audit_config/README.md
- k8s_audit_config/apiserver-config.patch.sh
- k8s_audit_config/audit-policy.yaml
- k8s_audit_config/audit-sink.yaml.in
- k8s_audit_config/enable-k8s-audit.sh
- k8s_audit_config/webhook-config.yaml.in
Copied from the falco instructions, these instructions show how to
enable k8s audit logging for the sysdig agent and minikube/kops.
> Docs to enable k8s audit for agent + minikube/kops

- agent_deploy/kubernetes/sysdig-agent-clusterrole.yaml
- agent_deploy/openshift/sysdig-agent-clusterrole.yaml
This reverts commit 35942a1024c90cd82d128ba49681772cdd4fdc8a.
Sysdig is no longer planning to add support for configmaps and secrets
in cointerface
> Revert "[SMAGENT-1517] k8s: add configmaps and secrets to sysdig clusterrole"

- agent_deploy/kubernetes/sysdig-agent-daemonset-v1.yaml
- agent_deploy/kubernetes/sysdig-agent-daemonset-v2.yaml
- agent_deploy/kubernetes/sysdig-agent-slim-daemonset-v1.yaml
- agent_deploy/kubernetes/sysdig-agent-slim-daemonset-v2.yaml
- agent_deploy/openshift/sysdig-agent-daemonset-redhat-openshift.yaml
This mounts /etc/modprobe.d in all daemonsets to prevent dkms from ignoring blacklists on the host machine.
> adding modprobe.d mounting to all daemonsets

- agent_deploy/IBMCloud-Kubernetes-Service/install-agent-k8s.sh
The script will fail immediately with the message "Please install sudo and re-run the script" if sudo is not present in the shell, like in some Docker containers. Sudo is only required for installing curl if it is not present, and since the [official IBM docs recommend downloading the script via curl](https://cloud.ibm.com/docs/services/Monitoring-with-Sysdig?topic=Sysdig-config_agent#config_agent_linux), most users won't ever hit that codepath.
> Remove hard sudo requirement

- agent_deploy/IBMCloud-Kubernetes-Service/install-agent-k8s.sh
This patches a problem with OpenShift clusters where the cluster name not parsed due to a change in the ibmcloud ks CLI behaviour.  The command `ibmcloud ks cluster-get <id>` has been removed and the correct command is `ibmcloud ks cluster get --cluster <id>`
> Version 1.0.0 of ks plugin drops support for cluster-get

- agent_deploy/IBMCloud-Kubernetes-Service/install-agent-k8s.sh
- Replaces check for specific `default-icr-io` name with a pattern match
Addresses draios/sysdig-cloud-scripts#110
> Updates the check for the IBM CR pull secret

- k8s_audit_config/audit-policy.yaml
Reflecting the changes in
https://github.com/falcosecurity/falco/pull/1153, this changes the
recommended audit policy to log secrets information at Metadata level,
which prevents the contents of secrets from being logged.
> Update audit level to Metadata for secrets

- agent_deploy/kubernetes/sysdig-agent-clusterrole.yaml
This change modifies the Agent's Cluster Role in order to allow the
retrieval of Kubernetes endpoint.
Signed-off-by: Lorenzo David <lorenzo.david@sysdig.com>
> [SSPROD-4035] Extend Agent RBAC capabilities to fetch endpoints

- agent_deploy/kubernetes/sysdig-image-analyzer-daemonset.yaml
This makes the behavior of the variable to skip ssl cert verification consistent with the agent
When the corresponding PR on the Image Analyzer repo is merged we'll be able to update this, and then we can mirror this change on the installer script as well.
> [SSPROD-4452] image analyzer: change the verify certificate variable name

- agent_deploy/IBMCloud-Kubernetes-Service/install-agent-k8s.sh
Hey @mbreitung this change has the correct commands for creating the IBM Cloud Container Registry secret needed to pull the Sysdig agent on OpenShift.
Technically those commands would be fine for IKS as well, but `ibmcloud ks cluster pull-secret` is cleaner
> Openshift instructions for creating ICR secret

- agent_deploy/IBMCloud-Kubernetes-Service/install-agent-k8s.sh
https://github.com/draios/sysdig-cloud-scripts/pull/127
https://github.com/draios/sysdig-cloud-scripts/issues/120
```shell
...
Processing all-icr-io as all-icr-io
secret/all-icr-io created
Processing default-icr-io as ibm-observe-icr-io
secret/ibm-observe-icr-io created
configmap/sysdig-agent created
* Deploying the sysdig agent
daemonset.apps/sysdig-agent created
sysdig-agent-gkrxx   1/1     Running   0          2m20s
sysdig-agent-l78qv   1/1     Running   0          2m20s
sysdig-agent-sb646   1/1     Running   0          2m20s
sysdig-agent-zg2sw   1/1     Running   0          2m20s
all-icr-io                 kubernetes.io/dockerconfigjson        1      4m18s
default-token-7t5zv        kubernetes.io/service-account-token   3      4m59s
ibm-observe-icr-io …
```
> Fix for deprecated kubectl get --export

- agent_deploy/kubernetes/sysdig-image-analyzer-daemonset.yaml
Newer versions of the image analyzer support containerd, this change allows the containerd socket to be configured from the configmap as well.
> SSPROD-4497 Env update for containerd support for the Node Image Analyzer

- agent_deploy/IBMCloud-Kubernetes-Service/install-agent-k8s.sh
This PR fixes the failing redeployment of Sysdig agents on IKS clusters.
---
<details>
<summary>Running the deployer script for the first time works fine.</summary>
```bash
$ ./install-agent-k8s.sh -a 7dde8cf6-4595-4967-ac04-6a0e577ce115 -c ingest.private.us-south.monitoring.cloud.ibm.com -ac 'sysdig_capture_enabled: false'
* Detecting operating system
* Downloading Sysdig cluster role yaml
* Downloading Sysdig config map yaml
* Downloading Sysdig daemonset v2 yaml
* Downloading Sysdig agent-slim daemonset v2 yaml
* Creating namespace: ibm-observe
* Creating sysdig-agent serviceaccount in namespace: ibm-observe
* Creating sysdig-agent clusterrole and binding
clusterrole.rbac.authorization.k8s.io/sysdig-agent created
* Creating sysdig-agent secret using the ACCESS_KEY provided
* Retreiving …
```
> fixed failing agent redeploy

- agent_deploy/kubernetes/sysdig-image-analyzer-daemonset.yaml
Use our public quay.io registry is preferable over dockerhub one.
> feat(image-analyzer): use quay.io registry

- k8s_audit_config/enable-k8s-audit.sh
1. kops get cluster was not declaring the $KOPS_CLUSTER_NAME so it was grabbing ALL clusters which caused errors when trying to merge and apply
2. Fix bug with the yq command to merge the cluster-current.yaml and merge.yaml as we had to specify that we want to append
> [SSPROD-5693] Fix bugs in the kops section

- agent_deploy/kubernetes/sysdig-image-analyzer-daemonset.yaml
In some cases, depending on the image content, NIA may take more memory to perform analysis. While these cases are fairly rare in our experience it could be beneficial to increase the default memory limit to prevent the pods from getting OOM killed.
> Increase NIA memory limit to 1.5GB

- agent_deploy/kubernetes/sysdig-agent-configmap.yaml
These values are alredy the defaults and don't need to be specifically
configured.
> Remove k8s audit options from sample configmap

- agent_deploy/kubernetes/sysdig-agent-daemonset-v1.yaml
- agent_deploy/kubernetes/sysdig-agent-daemonset-v2.yaml
- agent_deploy/kubernetes/sysdig-agent-slim-daemonset-v1.yaml
- agent_deploy/kubernetes/sysdig-agent-slim-daemonset-v2.yaml
- agent_deploy/kubernetes/sysdig-image-analyzer-daemonset.yaml
This is in part of the effort to move all Sysdig images to quay.io.
The changes here are only for the Vanilla k8s sample files.  We are not touching the IBM or Openshift files.
> Use quay.io registry for agent/slim-agent/node-image-analyzer

- agent_deploy/IBMCloud-Kubernetes-Service/install-agent-k8s.sh
- agent_deploy/kubernetes/sysdig-kmod-thin-agent-slim-daemonset.yaml
Daemonset and install agent script for IBM. Two possible options:
- By default: kmodule thin + agent slim
- Agent Full: Full agent
It's based on first step provided by @0snug0, and comments from his first PR  https://github.com/draios/sysdig-cloud-scripts/pull/147
> [QA-2299] IBM kmodule thin and agent slim

- agent_deploy/kubernetes/sysdig-benchmark-runner-configmap.yaml
- agent_deploy/kubernetes/sysdig-node-analyzer-daemonset.yaml
https://sysdig.atlassian.net/browse/SSPROD-6639
This PR adds a new `Node Analyser` daemonset to replace the existing `Node Image Analyzer`. This new daemonset contains the existing NIA container, as well as the new Benchmark Runner container. The sysdigcloud-image-analyzer-configmap is unchanged, and there is also an additional sysdigcloud-benchmark-runner-configmap applied as well. 
The single-line installer changes are in a PR here: https://github.com/draios/agent/pull/2481
Note: we will need to update the onboarding UI and the [documentation here](https://docs.sysdig.com/en/quick-install-sysdig-agent-on-kubernetes.html)
Please see https://sysdigcloud.slack.com/archives/C013QKAEQ2G/p1617211290072100 and https://sysdigcloud.slack.com/archives/C013QKAEQ2G/p1619085395165800 for more …
> SSPROD-6639 Update Single Line Installer to use more generic Node Analyzer

- agent_deploy/kubernetes/sysdig-benchmark-runner-configmap.yaml
- agent_deploy/kubernetes/sysdig-node-analyzer-daemonset.yaml
In order to support agent tags, we mount the agent configmap in to the benchmark container. The benchmark container (and the NIA container) already relies on the agent secret, so this is not a completely new dependency
We also fetch the k8s cluster name to avoid having to specify it twice, causing confusion and drift.
Benchmarks runner is updated here: https://github.com/draios/secure-backend/pull/3177
> Add agent configmap mount in benchmark-runner

- agent_deploy/kubernetes/sysdig-host-analyzer-configmap.yaml
- agent_deploy/kubernetes/sysdig-node-analyzer-daemonset.yaml
Add the Host Analyzer to the daemonset.
Note that 
* The overall requests for the CPU have been lowered in order not to hog the cluster's CPU.
* The schedule has been set in the CM with a daily default
> Add Host Analyzer to the Node Analyzer DS (SSPROD-7038)

- agent_deploy/kubernetes/sysdig-node-analyzer-daemonset.yaml
Verify_TLS is defaulted in the benchmark image, and does not need to be set in the configmap. Before this PR, not specifying `ssl_verify_certificate` in the benchmark configmap would cause a container config error
> Don't require TLS config in NA Benchmark config 

- k8s_audit_config/apiserver-config.patch.sh
- k8s_audit_config/audit-policy-v2.yaml
- k8s_audit_config/audit-policy.yaml
- k8s_audit_config/enable-k8s-audit.sh
Things done here:
* Now minikube-1.13 variant uses webhook too as audit sink has been deprecated and removed
* For k8s versions higher than 1.12 we use a v2 audit_policy file with the proper api version that it's not deprecated, moved from v1beta1 to v1 
* For kops and rke we use v2 version so we don't support anymore k8s 1.11 and 1.12
I need to validate this changes yet in minikube and kops I will update the PR when all the checks has been done
> Adapt k8s audit scripts and files so it work in k8s versions higher than 1.18

- agent_deploy/kubernetes/sysdig-agent-slim-daemonset-v2.yaml
- agent_deploy/kubernetes/sysdig-kmod-thin-agent-slim-daemonset.yaml
This replaces https://github.com/draios/sysdig-cloud-scripts/pull/156 (needed to change branch name)
> Add (commented out) eBPF support for agent-slim and sysdig-kmod-thin-agent-slim-daemonset

- agent_deploy/kubernetes/sysdig-host-analyzer-configmap.yaml
- agent_deploy/kubernetes/sysdig-node-analyzer-daemonset.yaml
Previously we let users configure which host base to use for host scanning. This is a bit confusing as the expected one is actually hard coded in the DS, so the configuration is not actually useable.
This needs to be translated in the Helm chart as well.
> Node analyzer: use host base provided by daemonset for host analyzer

- support_bundle/get_support_bundle.sh
When we use the get_support_bundle.sh script with the namespace sysdig-agent, there is no configmap called "sysdigcloud-config" and therefore when the command `kubectl ${KUBE_OPTS} get configmap sysdigcloud-config -o yaml | grep -v password > ${LOG_DIR}/config.yaml` is run the script exists without writing the tgz file
Adding just a || true this doesn't happen and the tgz file can be written
> [QA-2735] Prevent the script from exiting if configmap "sysdigcloud-config" doesn't exist

- agent_deploy/kubernetes/sysdig-agent-daemonset-v1.yaml
- agent_deploy/kubernetes/sysdig-agent-slim-daemonset-v1.yaml
- agent_deploy/kubernetes/sysdig-agent-slim-daemonset-v2.yaml
- agent_deploy/kubernetes/sysdig-kmod-thin-agent-slim-daemonset.yaml
- agent_deploy/kubernetes/sysdig-node-analyzer-daemonset.yaml
Thanks to @ctolon22 to let us know that dnsPolicy is missed.
As explained in https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy, when using hostNetwork as we do, it is mandatory using ClusterFirstWithHostNet, while the default value is ClusterFirst. This misconfiguration produces problem when resolving Kubernetes Service Names 
This PR fixes all the daemonset with this issue
Tested (except for V1 daemonset that I don know how to use them) using a fresh k8s created with OSC https://sysdig-jenkins.internal.sysdig.com/view/QA/job/QA-onprem/job/stack-creator/3406/
Details of tests here https://docs.google.com/document/d/156bkBfqAsPyKlQU7jem-gDictbYm-L2GJAmQOWLXYpM/edit
> [SMPROD-5326] Daemonset: Add dnsPolicy: ClusterFirstWithHostNet

- agent_deploy/kubernetes/sysdig-agent-daemonset-v2.yaml
- agent_deploy/kubernetes/sysdig-agent-slim-daemonset-v2.yaml
- agent_deploy/kubernetes/sysdig-kmod-thin-agent-slim-daemonset.yaml
Agent eBPF code requires access to the /sys/kernel/debug filesystem.
For certain kernel versions, this filesystem is not accessible by default
from within docker containers, so add a VolumeMount in the daemonset.
> [SMAGENT-3114] Add /sys/kernel/debug VolumeMount when eBPF is in use

- agent_deploy/kubernetes/sysdig-agent-clusterrole.yaml
We need to add permissions to the ClusterRole of the Sysdig Agent  to allow for collection of Kubelet metrics, specifically, Persistent Volume Claim metrics.
> [SMAGENT-3049] Add new resources to ClusterRole to support collection of Kubelet metrics

- agent_deploy/kubernetes/sysdig-agent-daemonset-v1.yaml
- agent_deploy/kubernetes/sysdig-agent-daemonset-v2.yaml
- agent_deploy/kubernetes/sysdig-agent-slim-daemonset-v1.yaml
- agent_deploy/kubernetes/sysdig-agent-slim-daemonset-v2.yaml
- agent_deploy/openshift/sysdig-agent-daemonset-redhat-openshift.yaml
Using the _downwardAPI_, the agent container will find some pod-level metadata, stored in files.
Namely, with this PR we are storing:
**pod namespace** in _/etc/podinfo/metadata/namespace_
**pod name** in _/etc/podinfo/metadata/name_
> Use downwardAPI for propagating pod metadata into containers

- agent_deploy/openshift/sysdig-agent-clusterrole.yaml
This PR align OpenShift clusterole with Kubernetes' one. Leases were missing in Openshift
> Add leases support on OpenShift clusterrole

- agent_deploy/kubernetes/sysdig-agent-daemonset-v2.yaml
- agent_deploy/kubernetes/sysdig-agent-slim-daemonset-v2.yaml
- agent_deploy/kubernetes/sysdig-kmod-thin-agent-slim-daemonset.yaml
To be able to use the agent from our artifactory (now it's in docker.io and so no imagePullSecret is needed), the agent daemonset (both regular and slim agent) has to be modified to include an imagePullSecret to enable to access to it.
This first PR is modifying the agent daemonsets, to include these parameter commented.
And a second PR will modify the install_agent_kubernetes, to be able to enable it.
> [SMAGENT-3306] Add imagePullSecret commented lines to agent daemonset

- agent_deploy/kubernetes/sysdig-agent-clusterrole.yaml
We need to add permissions to the ClusterRole of the Sysdig Agent to allow for collection of Kubelet metrics, specifically, Persistent Volume Claim metrics
> Add new resources to ClusterRole to support collection of Kubelet metrics

- agent_deploy/kubernetes/sysdig-agent-daemonset-v2.yaml
- agent_deploy/kubernetes/sysdig-agent-slim-daemonset-v2.yaml
- agent_deploy/kubernetes/sysdig-kmod-thin-agent-slim-daemonset.yaml
- agent_deploy/openshift/sysdig-agent-daemonset-redhat-openshift.yaml
This PR exposes the k8s node name to agent pods through an environment variable using [downward API](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/). This avoids the agent to run the node name discovery.
> [SMAGENT-3336] Expose k8s node name to agent pods using downward API

- agent_deploy/IBMCloud-Kubernetes-Service/install-agent-k8s.sh
This disables the node-selector on openshift projects and skips labeling the nodes, which is Red Hat's recommendation for projects deploying daemonsets.
> [SMAGENT-3213] use empty project node selector for Openshift

- agent_deploy/kubernetes/sysdig-agent-daemonset-v2.yaml
Due to how the `install-agent-kubernetes` script uncomments lines, it expects an indented list item for the BPF env. Easiest fix seemed to be to also indent the downward api var to match.
> SMAGENT-3408 make whitespace consistent for container env

- agent_deploy/kubernetes/sysdig-agent-slim-daemonset-v2.yaml
- agent_deploy/kubernetes/sysdig-kmod-thin-agent-slim-daemonset.yaml
- agent_deploy/openshift/sysdig-agent-daemonset-redhat-openshift.yaml
Updates `sysdig-agent-slim-daemonset-v2.yaml`, `sysdig-kmod-thin-agent-slim-daemonset.yaml`, and `sysdig-agent-daemonset-redhat-openshift.yaml`, though I am reasonably certain that last one isn't used by the install script.
> SMAGENT-3408 make whitespace consistent for container env 

- agent_deploy/IBMCloud-Kubernetes-Service/install-agent-k8s.sh
As with #189 , porting https://github.com/draios/agent/pull/2727 to allow a complete specification of the agent image, allowing
any agent image installation, maintaining the same defaults as before:
-  -ar : if provided, the registry for the agent images (default: icr.io)
- -arr : if provided, the repository for the agent image (default: ext/sysdig/agent)
- -asr : if provided, the repository for the agent-slim image (default: ext/sysdig/agent-slim)
- -akr : if provided, the repository for the agent-kmodule image (default: ext/sysdig/agent-kmodule)
> [QA-3764] Add flags to change the registry and image used in the agent

- support_bundle/get_support_bundle.sh
- /api/admin/customer/1/dataRetentionSettings
- metrics (syscall.count, dragent.analyzer.sr, container.count, dragent.analyzer.n_drops_buffer, dragent.analyzer.n_evts)
-  Get Agent Versions and Metric Limits data from the API to see how many metrics agents are indeed sending.
- cleaned up some variables to standardize on formatting (eg; $pod -> ${pod})
- Added mysql storage info (if it exists)
- Added ability to determine if container has **sh** or **bash** installed when we try collect logs using **tar** inside the container.
- Standardize on storage location for checks we are doing against the statefulsets.
- Add snapshotSettings API Call
- Add ElasticSearch SSL Certificate End Date Data Collection
- Add api/license Call if customer passes in API_KEY
- Refactor argument parsing 
- Add …
> update support bundle to include new data gathering

- support_bundle/get_support_bundle.sh
- After refactor, the namespace arg parsing was missed
- reverted the NAMESPACE default back to `sysdig` to match that of the installer
> [TSOPS-1185] Fix missing namespace arg parsing

- support_bundle/get_support_bundle.sh
JIRA: [https://sysdig.atlassian.net/browse/TSOPS-1226](https://sysdig.atlassian.net/browse/TSOPS-1226)
> [TSOPS-1226] Add API Call to List Users and Teams

- support_bundle/get_support_bundle.sh
The get_support_bundle.sh was failing in the jobs complaining about: `line 144: error: unbound variable` 
More details in this ticket: https://sysdig.atlassian.net/browse/QA-4702
We are just assigning value 0 to variable `error` as it seems that it doesn't have a default value on declaration
> in get_support_bundle assign value to error variable also in success path 

- agent_deploy/openshift/sysdig-agent-daemonset-redhat-openshift.yaml
- agent_deploy/openshift/sysdig-agent-service.yaml
https://sysdig.atlassian.net/browse/ESC-1499
Brings in mounts and toleration from the default k8s daemonset. Also copied over the service, since the setup instructions include it.
Tested with OCP 3.7 and 4.9
> Update OCP manifests

- support_bundle/get_support_bundle.sh
- https://sysdig.atlassian.net/browse/QA-5649
- https://sysdig.atlassian.net/browse/TSOPS-1341
- #211 
For the newest sysdig installation, `opensearch` is preferred (default value) to `elasticsearch`. This make the current implementation of the `get_support_bundle.sh` script to not work.
Since `opensearch` is an important part the infrastructure, this PR works on several fronts:
- Guarss every fetch command with a final `|| true`, to avoid any disruption of the script (as performed for other components)
- Removes the `-it` flag from the `kubectl exec` from elastic search (no interactive operations are required)
- Adapts the certificate path for the `ELASTIC_CURL` variable to `opensearch`
The PR has been tested against a couple of sysdig installation, one with ES6 and one with OpenSearch.
> [TSOPS-1341] Make get_support_bundle.sh compatible with opensearch

- agent_deploy/IBMCloud-Kubernetes-Service/install-agent-k8s.sh
Check for required Openshift APIs to auto-detect Openshift. This matches what was added to the regular `install-agent-kubernetes` script.
> Auto-detect Openshift in IBM installer script

- support_bundle/get_support_bundle.sh
It can happen that a pod listed in the previous steps is not present anymore when it comes its time during the for loop (CLBOs, eviction, etc.).
This causes the script to crash since it tries to access the non existen pod to retrieve the list of containers.
This commit is adding a safeguard for this kind of situation.
> [get_support_bundle.sh] Add safeguard when getting containers name from pod

- support_bundle/get_support_bundle.sh
When users ran this script on macOS, they received an error: 'illegal option -- d' 
Added ability to detect the OS and use the correct way to get EPOCH time for that OS. Tested on MacOS.
> [get_support_bundle.sh] Detect OS to get EPOCH time

- support_bundle/get_support_bundle.sh
https://sysdig.atlassian.net/browse/TSOPS-1431
Added the following to the support bundle script:
+ A check that will determine if the backend is on version 6
+ Adjusts the API URL depending on which version the backend is running
+ Gathers a list of configured Events from the API (request from CS team)
Tested on backends deployed with installers:
5.0.4-3 e210cc6c11e6ceeb3ea2125050262d793e8cccae 2022-02-07T14:17:53Z clean darwin amd64 gc 6.1.1-1-230302180628 69533efd2b181d2507cf5617201d879dde542ce6 2023-03-02T18:07:18Z clean darwin amd64 gc
> [TSOPS-1431] Version check, api_url fix, events

- support_bundle/get_support_bundle.sh
on-premise v6 we have individual configMaps per workload so we need to extract them independently for health checks/configuration validation
> [TSDEVOPS-51] Add configmap to object list of manifests

- support_bundle/get_support_bundle.sh
I have changed most of kubectl get pods commands to print out only the pod name directly by using "-o custom-columns=NAME:metadata.name" instead of using awk.
Before approving the PR is worth doing a quick test on different k8s version, I have test it only on k8s 1.23
> Use k8s custom-columns
