draios/sysdig-cloud-scripts

agent_deploy/kubernetes/sysdig-daemonset.yaml
agent_deploy/kubernetes/sysdig-rc.yaml

Fix issue 4

---

agent_deploy/kubernetes/sysdig-daemonset.yaml

1. imagePullPolicy: Always
2. nodriver option

Added imagePullPolicy and  nodriver option

---

agent_deploy/kubernetes/sysdig-secure-daemonset.yaml

Add a example daemonset config that creates a secure-enabled agent.

Reference daemonset config for secure

---

LDAP/README.md
LDAP/create_user
LDAP/env.sh
LDAP/login_config
LDAP/settings_login_group.json
LDAP/settings_login_group_deprecated.json
LDAP/settings_login_simple.json
LDAP/settings_login_with_user_create.json
LDAP/settings_user_create.json
LDAP/verify_user

These are a subset of the helper scripts already reviewed and approved in PR #22, covering just the portions we're planning to support in on-premises release #890. The remainder of the new functionality remains in beta for the time being.

Helper scripts for LDAP API config in release #890

---

agent_deploy/kubernetes/sysdig-agent-daemonset-v1.yaml
agent_deploy/kubernetes/sysdig-agent-slim-daemonset-v1.yaml
agent_deploy/kubernetes/sysdig-agent-slim-daemonset-v2.yaml

Changes to support upcoming variants of the sysdig agent that split building kernel module and running the agent.

Add slim agent

---

agent_deploy/IBMCloud-Kubernetes-Service/install-agent-k8s.sh

The description of the -cc parameter was wrong and caused some confusion.  This PR should clear it up.

Fix description for the -cc option

---

agent_deploy/kubernetes/sysdig-agent-slim-daemonset-v2.yaml

as it currently must be run inside k8s

add warning for agent-slim

---

SSO/LDAP/README.md
SSO/LDAP/beta/README.md
SSO/LDAP/beta/api_user_creation.sh
SSO/LDAP/beta/mapping_config.sh
SSO/LDAP/beta/settings_mapping_hybrid.json
SSO/LDAP/beta/settings_mapping_simple.json
SSO/LDAP/login_config.sh
SSO/LDAP/verify_user.sh

Also include small fix for existing scripts

Add user/team LDAP synchronisation script

---

agent_deploy/IBMCloud-Kubernetes-Service/install-agent-k8s.sh

Changes the Docker repo to IBM Cloud Container Registry (icr.io) and deals with the secrets needed to pull the image(s)
Adds agent-slim support

IBM Cloud CR and agent-slim/kmodule

---

agent_deploy/IBMCloud-Kubernetes-Service/install-agent-k8s.sh

Let the script take an option argument `agent-version` that will pull a specific version of the agent.

Supply agent version argument

---

CODEOWNERS

match pattern should support arbitrary depth

fix CODEOWNERS bug

---

agent_deploy/kubernetes/sysdig-agent-configmap.yaml
agent_deploy/openshift/sysdig-agent-configmap.yaml

Reverts draios/sysdig-cloud-scripts#101

Revert "SMPROD-2989 create default prometheus.yaml file"

---

agent_deploy/kubernetes/sysdig-image-analyzer-configmap.yaml
agent_deploy/kubernetes/sysdig-image-analyzer-daemonset.yaml

Add variables to the daemonset to enable native proxy support.

SSPROD-4650 Node Image Analyzer proxy support

---

agent_deploy/IBMCloud-Kubernetes-Service/install-agent-k8s.sh

This brings the NIA script PR in sync with the install script for other environments.

update k8s install script with containerd option for NIA

---

agent_deploy/IBMCloud-Kubernetes-Service/install-agent-k8s.sh

Update agent install script used in IBM environment, including the scanning local image analyzer.

update ibm k8s agent scripts - add local image analyzer

---

agent_deploy/kubernetes/sysdig-image-analyzer-configmap.yaml

- Adding example for collector_endpoint since it is required as reference

Add collector_endpoint example to image analyzer config map

---

agent_deploy/kubernetes/sysdig-agent-daemonset-v1.yaml
agent_deploy/kubernetes/sysdig-agent-daemonset-v2.yaml
agent_deploy/kubernetes/sysdig-agent-slim-daemonset-v1.yaml
agent_deploy/kubernetes/sysdig-agent-slim-daemonset-v2.yaml

See https://github.com/draios/sysdig/pull/1600

Add /etc/VERSION mount for Minikube

---

k8s_audit_config/enable-k8s-audit.sh

Create `stackdriver-webhook-bridge` secret in same deployment/configmap namespace

Create secret in the same namespace than stackdriver bridge in GKE

---

agent_deploy/IBMCloud-Kubernetes-Service/install-agent-k8s.sh

Corrected typo for quay.io

---

agent_deploy/kubernetes/sysdig-agent-clusterrole.yaml

Add an ApiGroup to ClusterRole to use leases to reduce Sysdig Agent load on API Server.

 [SMAGENT-3049]Add an ApiGroup to ClusterRole to use leases

---

agent_deploy/IBMCloud-Kubernetes-Service/install-agent-k8s.sh

Between others:
* Add support for the new node analyzer
* Improvement in the options, adding missing options in the help message
* Adding clean up things

Update IBM install k8s script with the latest additions

---

support_bundle/get_support_bundle.sh

The tool gets a list of all pods and then iterates over them to retrieve the logs of all containers inside. 
Under some circumstances a pod that was originally listed at the start can no longer exists when trying to get the logs. A good example of this are cronjob based pods.
To cover this corner we've added a `--ignore-not-found` param to kubectl pod and container listing, and disabled the log retrieval for non-existing pods.

[Quickfix] handle missing pods

---

SSO/README.md
user_creation/README.md

The README.md is linking to a very old documentation instead of the new site. Fix it.

Update documentation link

---

agent_deploy/IBMCloud-Kubernetes-Service/install-agent-k8s.sh

Following the changes done to the default installer by @alblasco in https://github.com/draios/agent/pull/2880 I'm porting them to
the IBM installer.

[SMAGENT-3306] Add --image_pull_secret flag to IBM installer

---

support_bundle/get_support_bundle.sh

JIRA Ticket:  [TSOPS-1180](https://sysdig.atlassian.net/browse/TSOPS-1180)
* Fixed error condition that causes script to fail when collecting POD information through kubectl
* Cleaned up logic block formatting so they all match

[TSOPS-1180] Fix error condition when collecting pod information

---

agent_deploy/IBMCloud-Kubernetes-Service/install-agent-k8s.sh

Address the failing install script when using MacOS reported in #192 and #195

Split sed into 2 separate commands to support MacOS

---

agent_deploy/kubernetes/sysdig-agent-daemonset-v2.yaml
agent_deploy/kubernetes/sysdig-agent-slim-daemonset-v2.yaml
agent_deploy/kubernetes/sysdig-kmod-thin-agent-slim-daemonset.yaml
agent_deploy/kubernetes/sysdig-node-analyzer-daemonset.yaml

Kubernetes v1.24/v1.25 taint changes

Added toleration to agent and node-analyzer yaml files

---

support_bundle/get_support_bundle.sh

[https://sysdig.atlassian.net/browse/TSOPS-1355](https://sysdig.atlassian.net/browse/TSOPS-1355)
Fail when customer provides Unauthorized API Token.
[TSOPS-1355]: https://sysdig.atlassian.net/browse/TSOPS-1355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TSOPS-1355]: https://sysdig.atlassian.net/browse/TSOPS-1355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TSOPS-1355] Fail on Unauthorized API Token

---

agent_deploy/kubernetes/sysdig-agent-daemonset-v2.yaml
agent_deploy/kubernetes/sysdig-agent-slim-daemonset-v2.yaml
agent_deploy/kubernetes/sysdig-image-analyzer-daemonset.yaml
agent_deploy/kubernetes/sysdig-kmod-thin-agent-slim-daemonset.yaml
agent_deploy/kubernetes/sysdig-node-analyzer-daemonset.yaml

https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
https://github.com/rancher/rancher/commit/5f6a1b857da7a61d4d9bd1e697b8ce14d8cf54e9

Add Rancher-specific tolerations to daemonset manifests

---

support_bundle/get_support_bundle.sh

Added collection of SSO settings when the administrative token is supplied.

Adding SSO setting collection

---

support_bundle/get_support_bundle.sh

Add 'kubectl cluster-info dump' to the support bundle.

[TSOPS-1406] Add TSOPS-1406

---

support_bundle/get_support_bundle.sh

Adding the BACKEND_VERSION variable, and adjusting API calls. The result is we only make API calls relevant to the backend version

Adding BACKEND_VERSION variable

---

support_bundle/get_support_bundle.sh

Adding scanning v1 and v2 endpoints when the Secure API is provided.

Added scanning endpoints

---

support_bundle/get_support_bundle.sh

It would be helpful to save the backend version.

Write backend version to 'backend_version.txt' & pod log dir
